baseURL = "https://tole.es"
title = "La sede de varios proyectos que tolean!"
theme = "dream"
languageCode = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
disableKinds = ["RSS"]
enableRobotsTXT = true
GoogleAnalytics = "G-1BKKRPRJ18"
[pagination]
pagerSize = 30

[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling

  description = "La sede de varios proyectos que tolean!"
  copyright = ""
  enableSearch = true
  highlightjs = true
  showSummaryCoverInPost = true
  sidebarAbout = []
  author = "Tole.es"
  # Enable Google Analytics by entering your tracking code
  gtag="G-1BKKRPRJ18"
  yandex = "c18f9bd7c16058ed"
  footerBottomText = "Images from unsplash.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
